version: '3.8' # Use 3.8 to support the deploy block correctly

services:
  solr:
    image: solr:9
    container_name: pri_solr
    ports:
      - "8983:8983"
    command: solr-precreate drugs


  frontend:
    build: ./frontend
    container_name: pri_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000